[config]
schemaVersion = "0.1.3"

[package]
namespace = "JoStro"
name = "json"
versionNumber = "0.1.3"
description = "Exposes json.lua as a module using lovely"
websiteUrl = "https://github.com/rxi/json.lua"
containsNsfwContent = false
[package.dependencies]
Thunderstore-lovely = "0.4.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./lovely.toml"
target = "lovely.toml"

[[build.copy]]
source = "./json.lua"
target = "json.lua"

[[build.copy]]
source = "./LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "balatro", ]
[publish.categories]
balatro = [ "libraries", ]


