# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch

  # Allows you to run this workflow manually from the Actions tab
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Create Release Zips
        run: |
          zip JoStro-Pack -r apis mods textures
          zip Parrot-Joker -r apis mods/parrot.lua textures/*x/parrot_joker_placeholder.png
          zip Buffoon-Deck -r apis mods/buffoon_deck.lua textures/*x/buffoon_deck.png

      - name: Create a Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: JoStro Pack ${{ github.ref_name }}
          artifacts: "*.zip"
          artifactContentType: application/zip
          
